spring:
  datasource:
    druid:
      db1:
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jt?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: pdwf122
        password: pdwf122
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@10.118.84.71/orcl
        initialSize: 5
        minIdle: 5
        maxActive: 20


#spring.datasource.druid.driver-class-name=oracle.jdbc.driver.OracleDriver  #可配可不配，阿里的数据库连接池会通过url自动搜寻
#spring.datasource.druid.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.druid.username=scott
#spring.datasource.druid.password=tiger
#spring.datasource.druid.initial-size=5
#spring.datasource.druid.max-active=20
#spring.datasource.druid.min-idle=10
#spring.datasource.druid.max-wait=10


#db1:
#  #      url: jdbc:mysql://10.118.24.75:3306/jt808?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
#  #      username: root
#  #      password: 123456
#  url: jdbc:mysql://127.0.0.1:3306/jt?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
#  username: root
#  password: root
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  type: com.alibaba.druid.pool.DruidDataSource
#  druid:
#    initial-size: 5
#    min-idle: 5
#    max-active: 20
#    # 配置获取连接等待超时的时间
#    max-wait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    time-between-eviction-runs-millis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    min-evictable-idle-time-millis: 300000
#    validation-query: SELECT 1 FROM DUAL
#    test-while-idle: true
#    test-on-borrow: false
#    test-on-return: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    pool-prepared-statements: true
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    max-pool-prepared-statement-per-connection-size: 20
#    filters: stat,wall
#    use-global-data-source-stat: true
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  db2:
#    driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@10.118.84.71/orcl
#      username: pdwf122
#      password: pdwf122
#      type: com.alibaba.druid.pool.DruidDataSource
#      dbcp2:
#        min-idle: 5
#        initial-size: 5
#        max-total: 15
#        max-wait-millis: 1000